# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cc2bded97dc1aca63e8a10da14bc99f82102a4a53ec5a4046bb825a95f101cf426900f869be3439edc1c75f120acc48cf2d7133280cddff493db132a6d70b09

test:
  secret_key_base: 9e7e31a8995b7343cd2380a6c3d580baeb5c99696b6d032ac5e2794643f5272ce55598992728434703ae3631d6dc28e560fb4cedb4056402db7f8c3822b998f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
